[source]
git = "https://github.com/THRAI/kernel.git"
rev = "f10c6cd30e5bc6c6f6e5def0817dc88179a61db6"

[build]
template = "custom"
script = """
cd "${COOKBOOK_SOURCE}"
make install BUILD="${COOKBOOK_BUILD}" DESTDIR="${COOKBOOK_STAGE}"
"""
